# -*- coding: utf-8 -*-
"""code final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7ZltaXCeLAg_eVuYIeC9joh6K0DOecy
"""

# ----------------------------
# 0. Imports
# ----------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import zipfile
from google.colab import files

# ----------------------------
# 1. Read uploaded files
# ----------------------------
user1_data = {
    'activewindows': pd.read_csv("activewindows.tsv", sep="\t"),
    'inactive': pd.read_csv("inactivity.tsv", sep="\t"),
    'keystrokes': pd.read_csv("keystrokes.tsv", sep="\t"),
    'mouse_mov_speeds': pd.read_csv("mouse_mov_speeds.tsv", sep="\t"),
    'mousedata': pd.read_csv("mousedata.tsv", sep="\t"),
    'usercondition': pd.read_csv("usercondition.tsv", sep="\t")
}

user2_data = {
    'activewindows': pd.read_csv("activewindows_2.tsv", sep="\t"),
    'inactive': pd.read_csv("inactivity_2.tsv", sep="\t"),
    'keystrokes': pd.read_csv("keystrokes_2.tsv", sep="\t"),
    'mouse_mov_speeds': pd.read_csv("mouse_mov_speeds_2.tsv", sep="\t"),
    'mousedata': pd.read_csv("mousedata_2.tsv", sep="\t"),
    'usercondition': pd.read_csv("usercondition_2.tsv", sep="\t")
}

# ----------------------------
# 2. Feature extraction functions
# ----------------------------
def extract_keystroke_features(df):
    df['Press_Time'] = pd.to_datetime(df['Press_Time'], errors='coerce')
    df['Relase_Time'] = pd.to_datetime(df['Relase_Time'], errors='coerce')
    df = df.dropna(subset=['Press_Time','Relase_Time'])

    if len(df) > 0:
        df['key_duration'] = (df['Relase_Time'] - df['Press_Time']).dt.total_seconds()
        avg_duration = df['key_duration'].mean()
        df = df.sort_values('Press_Time')
        df['inter_key'] = df['Press_Time'].diff().dt.total_seconds()
        avg_inter_key = df['inter_key'].mean()
        typing_speed = len(df) / (df['Press_Time'].max() - df['Press_Time'].min()).total_seconds()
    else:
        avg_duration = avg_inter_key = typing_speed = np.nan
    return avg_duration, avg_inter_key, typing_speed

def extract_mouse_features(df):
    df['Time'] = pd.to_datetime(df['Time'], errors='coerce')
    df = df.dropna(subset=['Time','X','Y'])

    if len(df) > 0:
        df = df.sort_values('Time')
        df['dx'] = df['X'].diff()
        df['dy'] = df['Y'].diff()
        df['distance'] = np.sqrt(df['dx']**2 + df['dy']**2)
        df['time_diff'] = df['Time'].diff().dt.total_seconds()
        df['speed'] = df['distance'] / df['time_diff']
        avg_speed = df['speed'].mean()
        total_distance = df['distance'].sum()
    else:
        avg_speed = total_distance = np.nan
    return avg_speed, total_distance

def extract_inactivity_features(df):
    df['Stopped_Time'] = pd.to_datetime(df['Stopped_Time'], errors='coerce')
    df['Activated_Time'] = pd.to_datetime(df['Activated_Time'], errors='coerce')
    df = df.dropna(subset=['Stopped_Time','Activated_Time','Duration(s)'])

    if len(df) > 0:
        avg_inactivity = df['Duration(s)'].mean()
        max_inactivity = df['Duration(s)'].max()
        total_inactivity = df['Duration(s)'].sum()
    else:
        avg_inactivity = max_inactivity = total_inactivity = np.nan
    return avg_inactivity, max_inactivity, total_inactivity

def extract_stress_features(df):
    if 'Stress_Val' in df.columns:
        stress_mapping = {
            'Neutral': 0,
            'S_Stressed': 1,
            'V_Stressed': 2,
            'F_Good': 3,
            'F_Great': 4
        }
        df['stress_numeric'] = df['Stress_Val'].map(stress_mapping).fillna(0)
        avg_stress = df['stress_numeric'].mean()
    else:
        avg_stress = np.nan
    return avg_stress

def extract_all_features(user_data):
    kd, ik, ts = extract_keystroke_features(user_data['keystrokes'])
    ms, td = extract_mouse_features(user_data['mousedata'])
    avg_inactivity, max_inactivity, total_inactivity = extract_inactivity_features(user_data['inactive'])
    stress = extract_stress_features(user_data['usercondition'])

    return {
        'avg_key_duration': kd,
        'avg_inter_key': ik,
        'typing_speed': ts,
        'avg_mouse_speed': ms,
        'total_mouse_distance': td,
        'avg_inactivity': avg_inactivity,
        'max_inactivity': max_inactivity,
        'total_inactivity': total_inactivity,
        'avg_stress': stress
    }

# ----------------------------
# 3. Extract features
# ----------------------------
user1_features = extract_all_features(user1_data)
user2_features = extract_all_features(user2_data)

print("User 1 Features:", user1_features)
print("User 2 Features:", user2_features)

# ----------------------------
# 4. Visualization with saving
# ----------------------------
def visualize_all(user_data, user_name):
    save_dir = f"{user_name}_plots"
    os.makedirs(save_dir, exist_ok=True)

    # 1. Stress distribution
    if 'Stress_Val' in user_data['usercondition'].columns:
        plt.figure(figsize=(6,4))
        sns.countplot(data=user_data['usercondition'], x='Stress_Val', order=user_data['usercondition']['Stress_Val'].value_counts().index)
        plt.title(f"{user_name} Stress Distribution")
        plt.savefig(f"{save_dir}/stress_distribution.png", dpi=300)
        plt.show()

    # 2. Typing speed over time
    df = user_data['keystrokes'].copy()
    df['Press_Time'] = pd.to_datetime(df['Press_Time'], errors='coerce')
    df = df.dropna(subset=['Press_Time'])
    if len(df) > 1:
        df['inter_key'] = df['Press_Time'].diff().dt.total_seconds()
        plt.figure(figsize=(8,4))
        plt.plot(df['Press_Time'], df['inter_key'], marker='o', linestyle='-', markersize=3)
        plt.title(f"{user_name} Inter-Key Time Over Time")
        plt.xlabel("Time")
        plt.ylabel("Inter-Key Duration (s)")
        plt.savefig(f"{save_dir}/inter_key_time.png", dpi=300)
        plt.show()

    # 3. Mouse speed over time
    df_mouse = user_data['mouse_mov_speeds'].copy()
    df_mouse['Time'] = pd.to_datetime(df_mouse['Time'], errors='coerce')
    df_mouse = df_mouse.dropna(subset=['Time','Speed(ms)'])
    plt.figure(figsize=(8,4))
    plt.plot(df_mouse['Time'], df_mouse['Speed(ms)'], marker='o', linestyle='-', markersize=3)
    plt.title(f"{user_name} Mouse Speed Over Time")
    plt.xlabel("Time")
    plt.ylabel("Speed (ms)")
    plt.savefig(f"{save_dir}/mouse_speed.png", dpi=300)
    plt.show()

    # 4. Inactivity histogram
    df_inact = user_data['inactive']
    plt.figure(figsize=(6,4))
    sns.histplot(df_inact['Duration(s)'], bins=10, kde=True)
    plt.title(f"{user_name} Inactivity Duration Distribution")
    plt.xlabel("Duration (s)")
    plt.ylabel("Frequency")
    plt.savefig(f"{save_dir}/inactivity_histogram.png", dpi=300)
    plt.show()

    # 5. Active applications count
    df_app = user_data['activewindows']
    app_counts = df_app['App_Name'].value_counts()
    plt.figure(figsize=(8,4))
    sns.barplot(x=app_counts.index, y=app_counts.values)
    plt.xticks(rotation=45)
    plt.title(f"{user_name} Active Applications Frequency")
    plt.ylabel("Count")
    plt.xlabel("Application")
    plt.savefig(f"{save_dir}/active_applications.png", dpi=300)
    plt.show()

    # 6. Mouse movement distance over time
    df_mouse_data = user_data['mousedata'].copy()
    df_mouse_data['Time'] = pd.to_datetime(df_mouse_data['Time'], errors='coerce')
    df_mouse_data = df_mouse_data.sort_values('Time')
    df_mouse_data['dx'] = df_mouse_data['X'].diff()
    df_mouse_data['dy'] = df_mouse_data['Y'].diff()
    df_mouse_data['distance'] = np.sqrt(df_mouse_data['dx']**2 + df_mouse_data['dy']**2)
    df_mouse_data['cum_distance'] = df_mouse_data['distance'].cumsum()
    plt.figure(figsize=(8,4))
    plt.plot(df_mouse_data['Time'], df_mouse_data['cum_distance'])
    plt.title(f"{user_name} Cumulative Mouse Distance Over Time")
    plt.xlabel("Time")
    plt.ylabel("Distance (pixels)")
    plt.savefig(f"{save_dir}/cum_mouse_distance.png", dpi=300)
    plt.show()

# Run visualization
visualize_all(user1_data, "User 1")
visualize_all(user2_data, "User 2")

# ----------------------------
# 5. Combine features for ML dataset
# ----------------------------
features_df = pd.DataFrame([user1_features, user2_features])
print("\nCombined Features DataFrame:")
print(features_df)

# ----------------------------
# 6. Zip all plots and download
# ----------------------------
with zipfile.ZipFile("eda_plots.zip", "w") as zipf:
    for user_name in ["User 1", "User 2"]:
        plot_dir = f"{user_name}_plots"
        for filename in os.listdir(plot_dir):
            filepath = os.path.join(plot_dir, filename)
            zipf.write(filepath, arcname=f"{user_name}/{filename}")

files.download("eda_plots.zip")